#!/usr/bin/env python3
"""Emit the generated nature data layer.

  lib/data/city-coordinates.ts     one corroborated coordinate per city
  lib/data/nature-classification.ts  one classification row per nearby place

Both files are generated; edit the generators, never the output.
"""
import json, sys, collections
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))
from taxonomy import CATEGORY_PRIORITY, TYPE_CATEGORIES  # noqa: E402

CACHE = HERE / "cache"
coords = json.load(open(CACHE / "city-coords.json"))
cls = json.load(open(CACHE / "classification.json"))
places = json.load(open(CACHE / "places-compact.json"))
types = json.load(open(CACHE / "place-types.json"))
PRIO = {c: i for i, c in enumerate(CATEGORY_PRIORITY)}
CONF = ["none", "low", "medium", "high"]


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


# ---------------------------------------------------------------- coordinates
rows = []
for slug in sorted(coords["coords"]):
    v = coords["coords"][slug]
    qid = f'"{v["qid"]}"' if v.get("qid") else "undefined"
    rows.append(f'  ["{slug}", {v["lat"]}, {v["lon"]}, {qid}],')
out = f'''import type {{ CityCoordinate }} from "@/types";

/**
 * One corroborated centre coordinate per indexed city.
 *
 * GENERATED by scripts/nature/resolve_city_coords.py + verify_city_coords.py.
 * Do not edit by hand.
 *
 * Each coordinate is a Wikidata P625 value for a settlement entity that was
 * chosen, not assumed: the corpus of curated nearby places carries its own
 * P625 coordinates and the city slugs each place was selected for, so the
 * correct entity for a city is the candidate whose connected places fall
 * inside the selection radius the corpus was built with. A namesake in
 * another region fails that test by hundreds of kilometres and is discarded.
 *
 * Coordinates exist so distances can be stated as measured great-circle
 * kilometres. They are never used to state a travel time.
 */
const rows: readonly (readonly [string, number, number, string | undefined])[] = [
{chr(10).join(rows)}
];

export const CITY_COORDINATES: ReadonlyMap<string, CityCoordinate> = new Map(
  rows.map(([citySlug, latitude, longitude, wikidataId]) => [
    citySlug,
    {{ citySlug, latitude, longitude, wikidataId }},
  ]),
);

export function getCityCoordinate(citySlug: string): CityCoordinate | undefined {{
  return CITY_COORDINATES.get(citySlug);
}}
'''
(ROOT / "lib/data/city-coordinates.ts").write_text(out)
print(f"city-coordinates.ts: {len(rows)} rows")

# ------------------------------------------------------------ classification
by_slug = {p["slug"]: p for p in places}
rows, stats = [], collections.Counter()
for slug in sorted(cls):
    v = cls[slug]
    mask = 0
    for c in v["categories"]:
        mask |= 1 << PRIO[c]
    # the type label that produced the primary category — real Wikidata
    # vocabulary, shown to the reader as "what kind of place is this"
    label = ""
    p = by_slug.get(slug)
    if p and v["primary"]:
        p31 = (types.get(p["qid"]) or {}).get("p31") or {}
        best = None
        for q, lab in sorted(p31.items()):
            cats = TYPE_CATEGORIES.get(q)
            if cats and v["primary"] in cats and lab:
                rank = cats.index(v["primary"])
                if best is None or rank < best[0]:
                    best = (rank, lab)
        if best is None:
            for q, lab in sorted(p31.items()):
                if q in TYPE_CATEGORIES and lab:
                    best = (0, lab)
                    break
        label = best[1] if best else ""
    conf = CONF.index(v["confidence"]) if v["confidence"] in CONF else 0
    stats[v["confidence"]] += 1
    for field in (slug, label):
        assert "|" not in field and "\n" not in field and "`" not in field and "\\" not in field, field
    rows.append(f"{slug}|{mask}|{conf}|{label}")

cat_list = ", ".join(f'"{c}"' for c in CATEGORY_PRIORITY)
out = f'''import type {{ NatureCategory, NatureClassification, NatureConfidence }} from "@/types";

/**
 * Nature classification for every curated nearby place.
 *
 * GENERATED by scripts/nature/classify.py from Wikidata structured types
 * (P31, plus one P279 hop). Do not edit by hand — edit
 * scripts/nature/taxonomy.py and regenerate.
 *
 * A place NAME never adds a category. "Lakeview Park" is typed `park`, so it
 * is a park; only structured type evidence can make something a lake. Names
 * are consulted in exactly one direction — to REMOVE a category that a type
 * would otherwise license.
 *
 * A place may hold several categories at once, which is deliberate: Mount
 * Fuji is typed `stratovolcano`, so it is a volcano AND a mountain and stays
 * answerable to "which mountains can I reach".
 *
 * Places with mask 0 carry no publishable nature category — they were either
 * vetoed as contamination or lack structured evidence — and are excluded from
 * every nature page.
 */
export const NATURE_CATEGORY_ORDER: readonly NatureCategory[] = [{cat_list}];

const CONFIDENCE_ORDER: readonly NatureConfidence[] = ["none", "low", "medium", "high"];

/**
 * One row per place: `placeSlug|categoryBitmask|confidenceIndex|typeLabel`.
 *
 * A single string rather than 32,543 array literals: as tuples this table
 * alone pushed `tsc --noEmit` past the default 4 GB heap, so `npm run
 * typecheck` would have needed a raised limit to stay green. Parsing costs one
 * pass at module load and keeps the type-check, the bundle parse, and the
 * build worker memory where they were.
 */
const TABLE = `\
{chr(10).join(rows)}`;

function decode(mask: number): NatureCategory[] {{
  const out: NatureCategory[] = [];
  for (let i = 0; i < NATURE_CATEGORY_ORDER.length; i += 1) {{
    if (mask & (1 << i)) out.push(NATURE_CATEGORY_ORDER[i]);
  }}
  return out;
}}

export const NATURE_CLASSIFICATION: ReadonlyMap<string, NatureClassification> = (() => {{
  const map = new Map<string, NatureClassification>();
  for (const line of TABLE.split("\\n")) {{
    if (!line) continue;
    const bar1 = line.indexOf("|");
    const bar2 = line.indexOf("|", bar1 + 1);
    const bar3 = line.indexOf("|", bar2 + 1);
    const placeSlug = line.slice(0, bar1);
    const categories = decode(Number(line.slice(bar1 + 1, bar2)));
    const typeLabel = line.slice(bar3 + 1);
    map.set(placeSlug, {{
      placeSlug,
      categories,
      primary: categories[0],
      confidence: CONFIDENCE_ORDER[Number(line.slice(bar2 + 1, bar3))],
      typeLabel: typeLabel || undefined,
    }});
  }}
  return map;
}})();

export function getNatureClassification(
  placeSlug: string,
): NatureClassification | undefined {{
  return NATURE_CLASSIFICATION.get(placeSlug);
}}
'''
(ROOT / "lib/data/nature-classification.ts").write_text(out)
print(f"nature-classification.ts: {len(rows)} rows  {dict(stats)}")
