import manifest from "@/lib/navigation/places-manifest.json";
import { PLACES_PUBLIC, placesCityUrl, placesIndexUrl } from "@/lib/navigation/ecosystem";

/**
 * Which cities have a published GCI Places hub.
 *
 * The manifest is GENERATED by the Places repository
 * (`npx tsx scripts/export-nav-manifest.ts`) from the same published-only
 * accessors its routes use, and committed here. That is the whole coupling
 * between the two products: a committed file, no runtime call, no shared
 * build.
 *
 * It is small on purpose — five cities today — and it is the reason a city
 * page can offer a city-specific Places link without ever inventing one. A
 * city that is not in this list gets the global Places surface or nothing at
 * all; it never gets /places/<its-slug>/.
 */
export interface PlacesCityEntry {
  gciCitySlug: string;
  placesCitySlug: string;
  name: string;
  countryName: string;
  path: string;
  publishedPlaces: number;
  publishedAreas: number;
  publishedCollections: number;
}

export const PLACES_MANIFEST_GENERATED_AT: string = manifest.generatedAt;

export const PLACES_CITIES: PlacesCityEntry[] = manifest.cities;

const byGciSlug = new Map(PLACES_CITIES.map((entry) => [entry.gciCitySlug, entry]));

/** True only when the city has a hub AND Places is live on the canonical domain. */
export function hasPlacesCity(citySlug: string): boolean {
  return PLACES_PUBLIC && byGciSlug.has(citySlug);
}

export function placesCityEntry(citySlug: string): PlacesCityEntry | undefined {
  return PLACES_PUBLIC ? byGciSlug.get(citySlug) : undefined;
}

/**
 * The honest Places link for one city:
 *  - its own hub when it has one,
 *  - the global Places surface when it does not,
 *  - nothing at all while Places is not publicly reachable.
 *
 * There is deliberately no fourth case. A city-shaped URL is never
 * constructed for a city the manifest does not list.
 */
export function placesLinkForCity(
  citySlug: string,
): { href: string; label: string; cityScoped: boolean } | null {
  if (!PLACES_PUBLIC) return null;
  const entry = byGciSlug.get(citySlug);
  if (entry) {
    return { href: placesCityUrl(entry.placesCitySlug), label: "Places", cityScoped: true };
  }
  return { href: placesIndexUrl(), label: "Places", cityScoped: false };
}
