/**
 * Safety & Quality-of-Life profiles for a city.
 *
 * All scores are deterministic, country- and signal-aware planning estimates
 * (0–100, higher = better) generated by scripts/generate-city-quality.py from
 * country priors blended with existing per-city signals (overall/air-quality/
 * energy/resilience scores, climate comfort, nearby-nature density, and
 * coastal/mountain cluster flags). They are NOT measured survey data, official
 * crime statistics, or live indices; do not edit by hand. Scoring formulas are
 * documented in the generator header.
 */
export interface CitySafetyProfile {
  crimeScore: number;
  personalSafetyScore: number;
  nightSafetyScore: number;
  roadSafetyScore: number;
  overallSafetyScore: number;
}

export interface CityQualityProfile {
  qualityOfLifeScore: number;
  healthcareScore: number;
  educationScore: number;
  greenSpaceScore: number;
  cleanlinessScore: number;
  infrastructureScore: number;
  mobilityScore: number;
}

export interface CityLifestyleProfile {
  familyFriendlyScore: number;
  digitalNomadScore: number;
  retirementScore: number;
  walkabilityScore: number;
  cyclingScore: number;
  outdoorLifestyleScore: number;
}

export interface CityQualityProfileRecord {
  citySlug: string;

  safety: CitySafetyProfile;
  quality: CityQualityProfile;
  lifestyle: CityLifestyleProfile;

  safetySummary: string;
  qualitySummary: string;
  familySummary: string;
  nomadSummary: string;
  retirementSummary: string;

  createdAt: string;
  updatedAt: string;
}
