/**
 * Economy profile for a city.
 *
 * All scores are deterministic, country- and signal-aware planning estimates
 * (0–100, higher = stronger) generated by scripts/generate-economy.py from
 * country economic priors blended with existing per-city signals (overall/
 * education/infrastructure/digital-nomad scores, cost level, metro size,
 * capital and airport status). They are NOT measured economic statistics, GDP
 * data, or live labour-market figures; do not edit by hand. Scoring formulas
 * and the industry/category rules are documented in the generator header.
 *
 * The four summary strings are stored alongside the scores (see the Phase D
 * "Economy summaries" requirement) and are likewise deterministic.
 */
export type EconomyCategory =
  | "global_hub"
  | "major_economy"
  | "regional_center"
  | "industrial_city"
  | "tourism_economy"
  | "government_center"
  | "education_research"
  | "mixed";

export interface EconomyProfile {
  citySlug: string;

  economyScore: number;

  employmentScore: number;
  salaryScore: number;
  startupScore: number;
  businessEnvironmentScore: number;

  remoteWorkScore: number;
  innovationScore: number;

  affordabilityAdjustedIncomeScore: number;

  dominantIndustries: string[];

  economyCategory: EconomyCategory;

  economySummary: string;
  jobsSummary: string;
  remoteWorkSummary: string;
  startupSummary: string;

  createdAt: string;
  updatedAt: string;
}
