/**
 * Education profile for a city.
 *
 * All scores are deterministic, country- and signal-aware planning estimates
 * (0–100, higher = stronger) generated by scripts/generate-education.py from
 * country academic priors blended with existing per-city signals (quality-of-life
 * education score, economy innovation/education-jobs scores, metro size, capital
 * and airport status). They are NOT measured education statistics, enrolment
 * figures, or institutional rankings; do not edit by hand. Scoring, category, and
 * university-generation rules are documented in the generator header.
 *
 * The four summary strings are stored alongside the scores (Phase E "Education
 * summaries" requirement) and are likewise deterministic.
 */
export type EducationCategory =
  | "global_academic_hub"
  | "major_university_city"
  | "research_center"
  | "student_city"
  | "regional_education_center"
  | "mixed";

export interface EducationProfile {
  citySlug: string;

  educationScore: number;

  higherEducationScore: number;
  researchScore: number;
  internationalStudentScore: number;

  studentFriendlinessScore: number;

  universityDensityScore: number;

  academicReputationScore: number;

  educationCategory: EducationCategory;

  educationSummary: string;
  studentExperienceSummary: string;
  researchSummary: string;
  internationalSummary: string;

  createdAt: string;
  updatedAt: string;
}
