import type { VerificationStatus } from "./emergency";

export type HealthcareSourceType =
  | "government_health_ministry"
  | "national_health_service"
  | "regional_health_authority"
  | "city_health_department"
  | "emergency_medical_service"
  | "international_public_health"
  | "official_hospital_registry";

export type HealthcareVerificationStatus = VerificationStatus;

export interface HealthcareLink {
  label: string;
  url: string;
  sourceIds: string[];
}

export interface HealthcareAccessProfile {
  countrySlug: string;
  countryCode: string;
  healthcareSystemName?: string;
  officialHealthPortal?: HealthcareLink;
  emergencyMedicalInfo?: string;
  publicHealthAuthority?: HealthcareLink;
  insuranceOrAccessNote?: string;
  lastVerified: string;
  dataYear?: string;
  sourceIds: string[];
  verificationStatus: HealthcareVerificationStatus;
}

export interface HospitalRegistryProfile {
  countrySlug: string;
  citySlug?: string;
  registryName?: string;
  registryUrl?: string;
  registryDescription?: string;
  sourceIds: string[];
  lastVerified: string;
  dataYear?: string;
  verificationStatus: HealthcareVerificationStatus;
}

export interface VerifiedHospital {
  id: string;
  citySlug: string;
  countrySlug: string;
  name: string;
  type?: string;
  emergencyDepartmentAvailable?: boolean;
  officialUrl?: string;
  address?: string;
  phone?: string;
  sourceIds: string[];
  lastVerified: string;
  verificationStatus: HealthcareVerificationStatus;
}

export interface CityHealthcareProfile {
  citySlug: string;
  countrySlug: string;
  healthcareAccessNote?: string;
  emergencyCareNote?: string;
  hospitalRegistryNote?: string;
  verifiedHospitalIds?: string[];
  lastVerified: string;
  dataYear?: string;
  sourceIds: string[];
  verificationStatus: HealthcareVerificationStatus;
}

/**
 * Phase F per-city healthcare profile (distinct from the verified, country-level
 * data above). All scores are deterministic, country- and signal-aware planning
 * estimates (0–100, higher = stronger) generated by scripts/generate-healthcare.py
 * from country healthcare priors blended with existing per-city signals. They are
 * NOT measured health statistics or clinical-outcome data; do not edit by hand.
 * The three summary strings are stored alongside the scores and are deterministic.
 */
export type HealthcareCategory =
  | "global_medical_hub"
  | "major_healthcare_center"
  | "regional_healthcare_center"
  | "healthcare_access_city"
  | "developing_healthcare_market"
  | "mixed";

export interface HealthcareProfile {
  citySlug: string;

  healthcareScore: number;

  healthcareAccessScore: number;
  hospitalAvailabilityScore: number;
  specialistCareScore: number;

  preventativeCareScore: number;
  emergencyCareScore: number;

  healthcareAffordabilityScore: number;

  healthcareCategory: HealthcareCategory;

  healthcareSummary: string;
  medicalAccessSummary: string;
  healthcareEnvironmentSummary: string;

  createdAt: string;
  updatedAt: string;
}
