/**
 * Jobs / labour-market profile for a city.
 *
 * All scores are deterministic, country- and signal-aware planning estimates
 * (0–100, higher = stronger) generated by scripts/generate-economy.py. They are
 * NOT measured employment statistics or live vacancy data; do not edit by hand.
 * Scoring formulas are documented in the generator header.
 */
export interface JobsProfile {
  citySlug: string;

  jobMarketScore: number;

  technologyJobsScore: number;
  healthcareJobsScore: number;
  financeJobsScore: number;
  manufacturingJobsScore: number;
  tourismJobsScore: number;
  educationJobsScore: number;

  remoteWorkAvailabilityScore: number;

  overallCareerOpportunityScore: number;

  createdAt: string;
  updatedAt: string;
}
