/**
 * City retirement-suitability profile.
 *
 * All scores are deterministic, signal-aware planning estimates (0–100, higher =
 * more suitable) generated by scripts/generate-healthcare.py from existing
 * per-city signals (quality-of-life retirement/safety/walkability scores, the
 * Phase F healthcare score, climate comfort, affordability, nature density). They
 * are NOT financial, medical, or relocation advice; do not edit by hand. The four
 * summary strings are stored alongside the scores (Phase F requirement) and are
 * deterministic.
 */
export type RetirementCategory =
  | "premium_retirement"
  | "active_retirement"
  | "affordable_retirement"
  | "urban_retirement"
  | "nature_retirement"
  | "mixed";

export interface RetirementProfile {
  citySlug: string;

  retirementScore: number;

  affordabilityScore: number;
  healthcareSupportScore: number;
  climateComfortScore: number;
  safetySupportScore: number;

  walkabilityScore: number;
  accessibilityScore: number;

  activeLifestyleScore: number;

  retirementCategory: RetirementCategory;

  retirementSummary: string;
  lifestyleSummary: string;
  affordabilitySummary: string;
  activeLivingSummary: string;

  createdAt: string;
  updatedAt: string;
}
