#!/usr/bin/env bash
# Manual/build-time ingestion helper for city-level air-quality data
# routed through the OpenAQ v3 platform.
#
# The script queries the OpenAQ v3 API for the latest measurement per
# (city, parameter) tuple, preserves the underlying official-publisher
# attribution that OpenAQ exposes via its provider/owner metadata, and
# prints a TypeScript record literal ready to be pasted into
#   lib/data/official/air-quality/dataset.ts.
#
# This script is NEVER invoked during page rendering. It is run
# manually when refreshing the dataset:
#
#   OPENAQ_API_KEY=your-key \
#     ./scripts/data/ingest-air-quality.sh > /tmp/air-quality.ts
#
# The OPENAQ_API_KEY environment variable is REQUIRED. Without it the
# script exits without emitting any records — the platform never
# fabricates air-quality values to fill the gap.
#
# Requires: curl, jq (both already installed on standard macOS / Linux).
#
# Accepted-source policy:
#   OpenAQ is used as the primary station-level aggregator. Every
#   emitted record cites OpenAQ AND the underlying publisher OpenAQ
#   reports for the station (typically a national environment agency
#   or a regulatory monitoring network — e.g. EEA national feeds, US
#   EPA AirNow, government open-data portals). When the underlying
#   publisher cannot be identified from OpenAQ's metadata, the record
#   is skipped rather than attributed to OpenAQ alone.

set -uo pipefail

API_BASE="https://api.openaq.org/v3"
RADIUS_METRES="25000"
LIMIT="25"

if [ -z "${OPENAQ_API_KEY:-}" ]; then
  echo "OPENAQ_API_KEY is not set; skipping all cities." >&2
  echo "// generated by scripts/data/ingest-air-quality.sh"
  echo "// OPENAQ_API_KEY was not set; no records emitted."
  echo "export const openaqRecords: AirQualityDatasetRecord[] = [];"
  exit 0
fi

# Target cities for the first verified batch. Each entry maps a
# platform city slug to its country slug and reference coordinates
# used by OpenAQ's geospatial location lookup. Coordinates are taken
# from each city's primary administrative centroid; OpenAQ resolves
# stations within RADIUS_METRES of the point.
declare -a CITIES=(
  # citySlug:countrySlug:lat:lon
  "copenhagen:denmark:55.6761:12.5683"
  "stockholm:sweden:59.3293:18.0686"
  "oslo:norway:59.9139:10.7522"
  "helsinki:finland:60.1699:24.9384"
  "amsterdam:netherlands:52.3676:4.9041"
  "berlin:germany:52.5200:13.4050"
  "paris:france:48.8566:2.3522"
  "london:united-kingdom:51.5074:-0.1278"
  "vienna:austria:48.2082:16.3738"
  "zurich:switzerland:47.3769:8.5417"
  "new-york:united-states:40.7128:-74.0060"
  "toronto:canada:43.6532:-79.3832"
  "vancouver:canada:49.2827:-123.1207"
  "tokyo:japan:35.6762:139.6503"
  "singapore:singapore:1.3521:103.8198"
  "sydney:australia:-33.8688:151.2093"
)

# Optional city filter (colon-separated slugs).
CITY_FILTER="${CITY_FILTER:-}"

# Parameters we want to ingest. OpenAQ exposes raw measurements; AQI
# is not computed by OpenAQ and is intentionally NOT requested here.
declare -a METRICS=(
  # openaqParameter:recordField
  "pm25:pm25"
  "pm10:pm10"
  "no2:no2"
  "o3:o3"
)

METRIC_FILTER="${METRIC_FILTER:-}"

# Strip a trailing comma+newline from a value if jq returned a string
# with quoting; emit the bare TS-safe form.
ts_string() {
  local raw="$1"
  raw="${raw//\\/\\\\}"
  raw="${raw//\"/\\\"}"
  echo "$raw"
}

# Locate a station near the city for the given parameter. Returns a
# JSON object with { locationId, providerName, locationName,
# lastUpdated } or "null" if none found.
locate_station() {
  local lat="$1"
  local lon="$2"
  local parameter="$3"
  local raw
  raw=$(curl -sS -4 --max-time 45 --retry 3 --retry-delay 2 \
    -H "X-API-Key: ${OPENAQ_API_KEY}" \
    "${API_BASE}/locations?coordinates=${lat},${lon}&radius=${RADIUS_METRES}&limit=${LIMIT}&parameters_id=&parameter=${parameter}" \
    2>/dev/null) || raw=""
  if [ -z "$raw" ]; then
    echo "null"
    return
  fi
  echo "$raw" | jq -c --arg param "$parameter" '
        .results // []
        | map(
            . as $loc
            | (.sensors // [])
            | map(select(.parameter.name == $param))
            | map({
                locationId: $loc.id,
                locationName: $loc.name,
                providerName: ($loc.provider.name // $loc.owner.name // ""),
                sensorId: .id,
                lastUpdated: ($loc.datetimeLast.utc // ""),
              })
          )
        | flatten
        | map(select(.providerName != ""))
        | sort_by(.lastUpdated)
        | last
        // null
      ' 2>/dev/null || echo "null"
}

# Fetch the latest measurement from a sensor. Returns { value, datetime } or null.
latest_measurement() {
  local sensorId="$1"
  local raw
  raw=$(curl -sS -4 --max-time 45 --retry 3 --retry-delay 2 \
    -H "X-API-Key: ${OPENAQ_API_KEY}" \
    "${API_BASE}/sensors/${sensorId}/measurements?limit=1&sort_order=desc" \
    2>/dev/null) || raw=""
  if [ -z "$raw" ]; then
    echo "null"
    return
  fi
  echo "$raw" | jq -c '
        .results // []
        | map(select(.value != null))
        | first
        // null
      ' 2>/dev/null || echo "null"
}

echo "// generated by scripts/data/ingest-air-quality.sh"
echo "// Records are reviewed manually before being committed."
echo "export const openaqRecords: AirQualityDatasetRecord[] = ["

for city in "${CITIES[@]}"; do
  IFS=":" read -r citySlug countrySlug lat lon <<<"$city"
  if [ -n "$CITY_FILTER" ]; then
    case ":${CITY_FILTER}:" in
      *":${citySlug}:"*) ;;
      *)
        continue
        ;;
    esac
  fi

  pm25_value=""
  pm10_value=""
  no2_value=""
  o3_value=""
  data_year=""
  last_updated=""
  providers=""

  for metric in "${METRICS[@]}"; do
    IFS=":" read -r parameter recordField <<<"$metric"
    if [ -n "$METRIC_FILTER" ]; then
      case ":${METRIC_FILTER}:" in
        *":${parameter}:"*) ;;
        *)
          continue
          ;;
      esac
    fi
    station=$(locate_station "$lat" "$lon" "$parameter")
    if [ -z "$station" ] || [ "$station" = "null" ]; then
      echo "// skipped ${citySlug}/${parameter}: no OpenAQ station with provider attribution" >&2
      continue
    fi
    sensorId=$(echo "$station" | jq -r '.sensorId')
    providerName=$(echo "$station" | jq -r '.providerName')
    measurement=$(latest_measurement "$sensorId")
    if [ -z "$measurement" ] || [ "$measurement" = "null" ]; then
      echo "// skipped ${citySlug}/${parameter}: no measurement value" >&2
      continue
    fi
    value=$(echo "$measurement" | jq -r '.value')
    datetime=$(echo "$measurement" | jq -r '.period.datetimeTo.utc // .datetime.utc // ""')
    year="${datetime:0:4}"
    day="${datetime:0:10}"

    case "$recordField" in
      pm25) pm25_value="$value" ;;
      pm10) pm10_value="$value" ;;
      no2) no2_value="$value" ;;
      o3) o3_value="$value" ;;
    esac

    if [ -z "$data_year" ] || [ "$year" \> "$data_year" ]; then
      data_year="$year"
    fi
    if [ -z "$last_updated" ] || [ "$day" \> "$last_updated" ]; then
      last_updated="$day"
    fi
    if [[ -n "$providerName" && ":${providers}:" != *":${providerName}:"* ]]; then
      if [ -z "$providers" ]; then
        providers="$providerName"
      else
        providers="${providers}:${providerName}"
      fi
    fi
  done

  if [ -z "$pm25_value" ] && [ -z "$pm10_value" ] && [ -z "$no2_value" ] && [ -z "$o3_value" ]; then
    echo "// skipped ${citySlug}: no verified measurements from OpenAQ" >&2
    continue
  fi

  providers_safe="$(ts_string "${providers//:/, }")"

  {
    echo "  {"
    echo "    citySlug: \"${citySlug}\","
    echo "    countrySlug: \"${countrySlug}\","
    [ -n "$pm25_value" ] && echo "    pm25: ${pm25_value},"
    [ -n "$pm10_value" ] && echo "    pm10: ${pm10_value},"
    [ -n "$no2_value" ] && echo "    no2: ${no2_value},"
    [ -n "$o3_value" ] && echo "    o3: ${o3_value},"
    echo "    dataYear: \"${data_year}\","
    echo "    lastUpdated: \"${last_updated}\","
    echo "    sourceIds: [\"openaq\"],"
    echo "    datasetId: AIR_QUALITY_DATASET_ID,"
    echo "    notes:"
    echo "      \"OpenAQ v3 station-level measurement; underlying publisher(s): ${providers_safe}. Review provider attribution before adding any non-OpenAQ source ids.\","
    echo "  },"
  }
done

echo "];"
