#!/usr/bin/env bash
# Manual/build-time ingestion helper for World Bank country indicators.
#
# Fetches the latest non-null observation per (country, indicator) tuple
# from the World Bank Data API and prints a TypeScript record literal
# ready to be pasted into
#   lib/data/official/country-indicators/dataset.ts.
#
# This script is NEVER invoked during page rendering. Run it manually
# when refreshing the dataset:
#
#   ./scripts/data/ingest-country-indicators.sh > /tmp/records.ts
#
# Requires: curl, jq (both already installed on standard macOS / Linux).

set -uo pipefail

API_BASE="https://api.worldbank.org/v2"
START="2018"
END="2025"

declare -a COUNTRIES=(
  # countrySlug:iso2:iso3:name
  "united-states:US:USA:United States"
  "united-kingdom:GB:GBR:United Kingdom"
  "canada:CA:CAN:Canada"
  "australia:AU:AUS:Australia"
  "germany:DE:DEU:Germany"
  "france:FR:FRA:France"
  "japan:JP:JPN:Japan"
  "singapore:SG:SGP:Singapore"
  "denmark:DK:DNK:Denmark"
  "netherlands:NL:NLD:Netherlands"
)

declare -a INDICATORS=(
  # wbCode:indicatorKey:label:unit
  "SP.POP.TOTL:population:Population:people"
  "IT.NET.USER.ZS:internet_usage:Internet usage:percent"
  "SP.URB.TOTL.IN.ZS:urban_population_share:Urban population share:percent"
  "NY.GDP.PCAP.CD:gdp_per_capita:GDP per capita:current US\$"
  "SP.DYN.LE00.IN:life_expectancy:Life expectancy:years"
  "SH.XPD.CHEX.PC.CD:health_expenditure:Health expenditure per capita:current US\$"
  "SL.UEM.TOTL.ZS:unemployment_rate:Unemployment rate:percent"
  # The legacy indicator EN.ATM.CO2E.PC was archived by the World
  # Bank; the current published replacement is the AR5-based
  # EN.GHG.CO2.PC.CE.AR5 (Carbon dioxide emissions excluding LULUCF
  # per capita, t CO2e/capita).
  "EN.GHG.CO2.PC.CE.AR5:co2_emissions_per_capita:CO₂ emissions per capita:metric tons per capita"
  "IT.NET.BBND.P2:digital_access:Fixed broadband subscriptions:per 100 people"
)

# Optional indicator filter: set INDICATOR_FILTER to a colon-separated
# list of indicatorKey values to limit emission. Useful when refreshing
# a single batch without touching the rest.
INDICATOR_FILTER="${INDICATOR_FILTER:-}"

last_observation() {
  local iso3="$1"
  local code="$2"
  local raw
  raw=$(curl -sS -4 --max-time 45 --retry 3 --retry-delay 2 \
    "${API_BASE}/country/${iso3}/indicator/${code}?format=json&per_page=20&date=${START}:${END}" \
    2>/dev/null) || raw=""
  if [ -z "$raw" ]; then
    echo "null"
    return
  fi
  echo "$raw" | jq -c '
        if (.[1] // []) | length == 0 then
          null
        else
          .[1]
          | map(select(.value != null))
          | sort_by(.date)
          | last
        end
      ' 2>/dev/null || echo "null"
}

dataset_lastupdated() {
  local iso3="$1"
  local code="$2"
  local raw
  raw=$(curl -sS -4 --max-time 45 --retry 3 --retry-delay 2 \
    "${API_BASE}/country/${iso3}/indicator/${code}?format=json&per_page=1&date=${START}:${END}" \
    2>/dev/null) || raw=""
  if [ -z "$raw" ]; then
    echo ""
    return
  fi
  echo "$raw" | jq -r '.[0].lastupdated // ""' 2>/dev/null || echo ""
}

emit_record() {
  local slug="$1"
  local iso2="$2"
  local key="$3"
  local label="$4"
  local unit="$5"
  local value="$6"
  local year="$7"
  local lastUpdated="$8"
  local wbCode="$9"
  cat <<TS
  {
    countrySlug: "${slug}",
    countryCode: "${iso2}",
    indicatorKey: "${key}",
    label: "${label}",
    value: ${value},
    unit: "${unit}",
    dataYear: "${year}",
    lastUpdated: "${lastUpdated}",
    sourceIds: ["world-bank-wdi"],
    datasetId: COUNTRY_INDICATOR_DATASET_ID,
    verificationStatus: "verified",
    notes:
      "World Bank indicator ${wbCode}; source-attributed, no transformation beyond normalization.",
  },
TS
}

echo "// generated by scripts/data/ingest-country-indicators.sh"
echo "export const worldBankRecords: CountryIndicatorRecord[] = ["

for country in "${COUNTRIES[@]}"; do
  IFS=":" read -r slug iso2 iso3 _name <<<"$country"
  for indicator in "${INDICATORS[@]}"; do
    IFS=":" read -r wbCode key label unit <<<"$indicator"
    if [ -n "$INDICATOR_FILTER" ]; then
      case ":${INDICATOR_FILTER}:" in
        *":${key}:"*) ;;
        *)
          continue
          ;;
      esac
    fi
    obs=$(last_observation "$iso3" "$wbCode")
    if [ -z "$obs" ] || [ "$obs" = "null" ]; then
      echo "// skipped ${slug}/${key}: no value returned" >&2
      continue
    fi
    value=$(echo "$obs" | jq -r '.value')
    year=$(echo "$obs" | jq -r '.date')
    lastUpdated=$(dataset_lastupdated "$iso3" "$wbCode")
    if [ -z "$lastUpdated" ]; then
      lastUpdated="$year-01-01"
    fi
    emit_record "$slug" "$iso2" "$key" "$label" "$unit" "$value" "$year" "$lastUpdated" "$wbCode"
  done
done

echo "];"
