#!/usr/bin/env python3
"""
Post-process generated image records:
  - drop flags, emblems, dictionary covers, book covers, and other non-landscape files
  - clean HTML entities and "(talk · contribs)" suffixes from author names
  - emit final lib/data/media/{city,country}-images.ts

Run AFTER verify-place-images.py.
"""

from __future__ import annotations

import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_DIR = os.path.join(ROOT, "lib", "data", "media")

# Reject when the Commons filename matches any of these tokens — flags,
# emblems, dictionary covers, etc. are not suitable hero imagery.
BAD_FILE_TOKENS = (
    "flag",
    "coat_of_arms",
    "coat-of-arms",
    "emblem",
    "wappen",
    "seal_of_",
    "dannebrog",       # Danish flag (proper name)
    "tricolour",
    "tricolore",
    "_deckel",         # Austrian dictionary cover slipped in via Wikidata P18
    "woerterbuch",
    "_cover",
    "_culture.",       # cultural montages may include identifiable people
    "_montage",
)


def file_is_unsuitable(src: str) -> bool:
    name = src.rsplit("/", 1)[-1].lower()
    return any(token in name for token in BAD_FILE_TOKENS)


def clean_author(author: str) -> str:
    if not author:
        return author
    a = html.unescape(author)
    a = re.sub(r"\s*\(talk(?:\s*[·•|]\s*contribs)?\)\s*", "", a)
    a = re.sub(r"\s*\(talk\)\s*", "", a)
    a = re.sub(r"\s+", " ", a).strip()
    return a


def ts_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def ts_record(record: dict) -> str:
    indent = "    "
    lines = ["  {"]
    order = [
        "id",
        "placeSlug",
        "placeType",
        "imageType",
        "src",
        "width",
        "height",
        "alt",
        "caption",
        "source",
        "sourceUrl",
        "author",
        "authorUrl",
        "license",
        "licenseUrl",
        "attributionText",
        "verified",
        "verifiedAt",
        "notes",
    ]
    for key in order:
        if key not in record:
            continue
        value = record[key]
        if isinstance(value, bool):
            lines.append(f"{indent}{key}: {'true' if value else 'false'},")
        elif isinstance(value, (int, float)):
            lines.append(f"{indent}{key}: {value},")
        elif value is None:
            continue
        else:
            lines.append(f"{indent}{key}: {ts_string(str(value))},")
    lines.append("  },")
    return "\n".join(lines)


def emit_ts(records: list[dict], const_name: str, out_path: str, place_label: str) -> None:
    header = (
        "import type { PlaceImage } from \"@/types\";\n\n"
        "/**\n"
        f" * Verified hero imagery for indexed {place_label}. Records are only added\n"
        " * when the source URL, author, and license can be confirmed against the\n"
        " * original Wikimedia Commons file page or provider page.\n"
        " * See /docs/image-sourcing.md for the verification workflow.\n"
        " *\n"
        f" * {place_label.capitalize()} without a verified record render the designed\n"
        " * fallback block defined in /components/media/ImageFallback.tsx.\n"
        " *\n"
        " * Generated by scripts/build-place-images.py — re-run after updating\n"
        " * the verifier or after upstream license metadata changes.\n"
        " */\n"
    )
    if not records:
        body = f"export const {const_name}: PlaceImage[] = [];\n"
    else:
        body = f"export const {const_name}: PlaceImage[] = [\n"
        body += "\n".join(ts_record(r) for r in records) + "\n];\n"
    with open(out_path, "w") as f:
        f.write(header + body)


def process(input_path: str, place_label: str) -> list[dict]:
    with open(input_path) as f:
        records = json.load(f)

    cleaned: list[dict] = []
    for r in records:
        if file_is_unsuitable(r.get("src", "")):
            print(
                f"  drop {place_label}/{r.get('placeSlug')}: unsuitable file ({r['src'].rsplit('/', 1)[-1]})",
                file=sys.stderr,
            )
            continue
        author = clean_author(r.get("author", ""))
        if not author:
            print(
                f"  drop {place_label}/{r.get('placeSlug')}: empty author after cleanup",
                file=sys.stderr,
            )
            continue
        r["author"] = author
        if r.get("license"):
            r["attributionText"] = f"{author} / Wikimedia Commons, {r['license']}"
        else:
            r["attributionText"] = f"{author} / Wikimedia Commons"
        cleaned.append(r)
    return cleaned


def main():
    city_records = process(
        os.path.join(MEDIA_DIR, "city-images.generated.json"), "city"
    )
    country_records = process(
        os.path.join(MEDIA_DIR, "country-images.generated.json"), "country"
    )

    emit_ts(
        city_records,
        "cityImages",
        os.path.join(MEDIA_DIR, "city-images.ts"),
        "cities",
    )
    emit_ts(
        country_records,
        "countryImages",
        os.path.join(MEDIA_DIR, "country-images.ts"),
        "countries",
    )

    print(f"\nFinal: {len(city_records)} city records, {len(country_records)} country records")


if __name__ == "__main__":
    main()
